### ISSUE TITLE
open-dev-tools open for whole Electron window?

### ISSUE THREAD

**Issue by mmontone** [neomacs-project/neomacs#71] opened 2024-11-26 18:38 UTC
Is it possible to make open-dev-tools open the dev tools for the whole Electron window, not for an individual buffer?

**Comment by kchanqvq** [comment] 2024-11-26 19:01
Do you mean the frame-root buffer (responsible for window management)? `(with-current-buffer (current-frame-root) (open-dev-tools))`

**Comment by mmontone** [comment] 2024-11-26 19:06
Yes .. does not seem to work for inspecting the buffer contents HTML, though?

**Comment by mmontone** [comment] 2024-11-26 19:14
My purpose is: open the tool once, then be able to inspect any buffer. Perhaps that is not going to work because of how neomacs Electron gui is built ...

**Comment by kchanqvq** [comment] 2024-11-26 19:19
Oh, that’s because the frame-root buffer is only responsible for window management. A Neomacs window is not a single webview/HTML document, instead every buffer has its own independent HTML document. A Neomacs window displays multiple such documents. This is what make it possible to use Neomacs as a browser (each web page ought to be displayed in separate views).

This is currently partly documented in window management section of the manual.

Closing the issue for now because it's not a bug, but feel free to continue the discussion!

**Closed by kchanqvq** 2024-11-26 19:19 UTC
